### ISSUE TITLE
Bazel Build Failed

### ISSUE THREAD

**Issue by Eulerianial** [tensorflow/deepmath#17]
In running the command: "bazel build ..."
I am seeing following error. Note sure what is causing it. 
...........
ERROR: /private/var/tmp/_bazel_USER/3498234242c6f7373b6edebcb02e157b/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false.
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors.
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors.

**Comment by zhzhang2012** [comment]
I had the same issue. You need to use bazel version `0.5.4`.

**Comment by Eulerianial** [comment]
@zhzhang2012 Thank you so much! May I know if tensorflow is already installed, do we have to still do ./configure while installing it?

**Comment by kbansal** [comment]
Should be fixed now, see Dockerfile for updated build instructions.
