### ISSUE TITLE
Example prover_options file to run DeepHOL via docker?

### ISSUE THREAD

**Issue by jasonrute** [tensorflow/deepmath#24]
I arrived at this repo via the [HOList website](https://sites.google.com/view/holist/home).  As someone with both knowledge of machine learning and HOL Light, I was hoping to play around with your new DeepHOL system.  However, it looks like I need a prover options file to run it:

```--prover_options=/tmp/example/prover_options.txt```

Can you provide an example file either in this GitHub repo or via the HOList website?  Thanks!

(Also, I noticed you recently gave two talks on this project at the [2019 AITP conference](http://aitp-conference.org/2019/).  It looks like many of the presenters shared their slides on the conference website.  If you are willing to do the same, it would help a lot.)

**Comment by kbansal** [comment]
Hi Jason,

Thanks for your interest. We are working on that, will leave this open for now and update here once we have made that available.

(Thanks for the suggestion, will look into that as well.)

**Comment by kbansal** [comment]
> I arrived at this repo via the [HOList website](https://sites.google.com/view/holist/home). As someone with both knowledge of machine learning and HOL Light, I was hoping to play around with your new DeepHOL system. However, it looks like I need a prover options file to run it:
> 
> `--prover_options=/tmp/example/prover_options.txt`
> 
> Can you provide an example file either in this GitHub repo or via the HOList website? Thanks!
> 

http://deephol.org has been updated. deepmath_deephol_benchmark.zip contains an example.

> (Also, I noticed you recently gave two talks on this project at the [2019 AITP conference](http://aitp-conference.org/2019/). It looks like many of the presenters shared their slides on the conference website. If you are willing to do the same, it would help a lot.)

Done.
http://aitp-conference.org/2019/slides/KBCS.pdf
http://aitp-conference.org/2019/slides/SL.pdf
