### ISSUE TITLE
name resolution failure when running prover_options.textpb

### ISSUE THREAD

**Issue by edatibm** [tensorflow/deepmath#27]
ed@ed-Aspire-E5-575:/tmp/deepmath/deephol$ sudo docker run -it --network=holist_net -v /tmp/deepmath:/data gcr.io/deepmath/deephol --prover_options=/data/deephol/example/prover_options.textpb --output=/data/prooflog.textpb --proof_assistant_server_address=holist:2000
W0521 16:32:38.697212 139814335006464 prover_flags.py:122] builtin_library is deprecated. Do not provide.
I0521 16:32:38.697877 139814335006464 prover_flags.py:137] Using prover_options:
 path_theorem_database: "/data/deephol/theorem_database_v1.0.textpb"
path_model_prefix: "/data/deephol/checkpoints/loop_tac_depend_5210000/model.ckpt-5210000"
path_tactics: "/data/deephol/example/hollight_tactics.textpb"
path_tactics_replace: "/data/deephol/example/hollight_tactics_replacements_nogen.textpb"
theorem_embeddings: "/data/loop_tac_depend_5210000__model.ckpt-5210000__v1.0__embedding.npy"
prover: "bfs"
bfs_options {
  max_top_suggestions: 20
  max_successful_branches: 5
  max_explored_nodes: 120
}
splits_to_prove: VALIDATION
timeout_seconds: 120.0
model_architecture: PARAMETERS_CONDITIONED_ON_TAC
library_tags: "clifford.ml"

I0521 16:32:38.698731 139814335006464 prover_flags.py:155] Splits to prove: VALIDATION
I0521 16:32:38.698900 139814335006464 prover_flags.py:170] Library tags to prove: clifford.ml
I0521 16:32:38.709361 139814335006464 io_util.py:85] Successfully read tactics from "/data/deephol/example/hollight_tactics.textpb"
I0521 16:32:38.709577 139814335006464 io_util.py:118] Found 41 tactics.
I0521 16:32:38.711959 139814335006464 io_util.py:85] Successfully read replacements from "/data/deephol/example/hollight_tactics_replacements_nogen.textpb"
I0521 16:32:38.712185 139814335006464 io_util.py:123] Found 3 tactic replacements.
I0521 16:33:40.346311 139814335006464 io_util.py:134] Successfully read theorem database from /data/deephol/theorem_database_v1.0.textpb (31680 theorems).
I0521 16:33:40.346585 139814335006464 prover_util.py:490] Generating task list for theorem database.
I0521 16:33:40.412294 139814335006464 prover_flags.py:189] Number of prover tasks: 16
I0521 16:34:41.991417 139814335006464 io_util.py:134] Successfully read theorem database from /data/deephol/theorem_database_v1.0.textpb (31680 theorems).
I0521 16:34:42.002013 139814335006464 io_util.py:85] Successfully read tactics from "/data/deephol/example/hollight_tactics.textpb"
I0521 16:34:42.002218 139814335006464 io_util.py:118] Found 41 tactics.
I0521 16:34:42.003573 139814335006464 io_util.py:85] Successfully read replacements from "/data/deephol/example/hollight_tactics_replacements_nogen.textpb"
I0521 16:34:42.003768 139814335006464 io_util.py:123] Found 3 tactic replacements.
2019-05-21 16:34:42.014507: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
I0521 16:34:42.015912 139814335006464 holparam_predictor.py:78] Importing from metagraph in /data/deephol/checkpoints/loop_tac_depend_5210000/export/best_exporter/1549098420/saved_model.pb.
W0521 16:34:45.323910 139814335006464 deprecation.py:323] From /home/main.runfiles/org_tensorflow/tensorflow/python/training/saver.py:1277: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I0521 16:34:45.324696 139814335006464 saver.py:1281] Restoring parameters from /data/deephol/checkpoints/loop_tac_depend_5210000/model.ckpt-5210000
I0521 16:34:45.540045 139814335006464 embedding_store.py:86] Reading embeddings from "/data/loop_tac_depend_5210000__model.ckpt-5210000__v1.0__embedding.npy"
I0521 16:34:46.395910 139814335006464 prover.py:357] Setting up and registering theorems with proof assistant...
Traceback (most recent call last):
  File "/home/main.runfiles/deepmath/deepmath/deephol/main.py", line 28, in <module>
    tf.app.run(main)
  File "/home/main.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/main.runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/main.runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/main.runfiles/deepmath/deepmath/deephol/main.py", line 24, in main
    prover_runner.run_pipeline(*prover_flags.process_prover_flags())
  File "/home/main.runfiles/deepmath/deepmath/deephol/prover_runner.py", line 31, in run_pipeline
    this_prover = prover.create_prover(prover_options)
  File "/home/main.runfiles/deepmath/deepmath/deephol/prover.py", line 348, in create_prover
    hol_wrapper = setup_prover(theorem_database)
  File "/home/main.runfiles/deepmath/deepmath/deephol/prover.py", line 361, in setup_prover
    proof_assistant_pb2.RegisterTheoremRequest(theorem=thm))
  File "/home/main.runfiles/deepmath/deepmath/deephol/public/proof_assistant.py", line 42, in RegisterTheorem
    return self.stub.RegisterTheorem(request)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Name resolution failure"
	debug_error_string = "{"created":"@1558456486.421764398","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2267,"referenced_errors":[{"created":"@1558456486.421761906","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/request_routing.cc","file_line":166,"grpc_status":14}]}"
>

**Comment by kbansal** [comment]
Do you have the proof assistant running? From the [website](http://deephol.org):

```
docker network create holist_net
docker run -d --network=holist_net --name=holist gcr.io/deepmath/hol-light
```

**Comment by edatibm** [comment]
Thank you. Yes and no. Problem was I had several dead docker containers all of the same thing. I cleaned up docker and restarted it and all is working.
