### ISSUE TITLE
Prove using multiple CPUs?

### ISSUE THREAD

**Issue by edatibm** [tensorflow/deepmath#29]
Is it possible to run the prover with multiple CPUs? I have 50 CPUs but only one is being used.

**Comment by kbansal** [comment]
Sorry for the delayed response.

Our code for distributed proving does not work outside the Google infrastructure as it relies on the Google-internal runner of Apache Beam pipelines. For reference, one can take a look at the [loop's prover_runner](https://github.com/tensorflow/deepmath/blob/master/deepmath/deephol/deephol_loop/prover_runner.py).
