### ISSUE TITLE
S-expression generation

### ISSUE THREAD

**Issue by NikolasTzimoulis** [tensorflow/deepmath#31]
I can't find anything in the HOList paper about how you generated the S-expressions for the theorem database. I'm assuming they are just lightly processed terms from HOL-Light's internal representation? I would like to make my own mini database. Is there anywhere I can find more information on the conversion or a specification of the format?

**Comment by spolu** [comment]
@NikolasTzimoulis this conversation may provide you more context on these questions: https://leanprover.zulipchat.com/#narrow/stream/219941-Machine-Learning.20for.20Theorem.20Proving/topic/HOList

**Comment by NikolasTzimoulis** [comment]
@spolu Thanks for your answer. I read through the thread and while it explains why the use of these S-expressions was chosen, it doesn't really explain exactly how I can convert between S-expressions and HOL Light's internal representation.

**Comment by kbansal** [comment]
@NikolasTzimoulis It is in printer.ml, I will try to find more specific pointers tomorrow if you haven't by then already

**Comment by kbansal** [comment]
Just realized it is a different repo so just saying printer.ml might have been confusing: https://github.com/brain-research/hol-light/blob/master/printer.ml

**Comment by kbansal** [comment]
Christian sent you more specific pointers over email, so I will close this for now. Feel free to reopen if need any other help with creating your own theorem database.

For anyone else running across this thread later, the methods are in "Parseable S-Expression printers" section of printer.ml ([link](https://github.com/brain-research/hol-light/blob/35956b7edf34b1ba3fb5c54f4eb108ab08eada03/printer.ml#L633)), and the Protobuf printer file ([pbprinter.ml](https://github.com/brain-research/hol-light/blob/master/pb_printer.ml)).
