### ISSUE TITLE
About the "missing" sub-package in deephol/deephol_loop

### ISSUE THREAD

**Issue by zhou745** [tensorflow/deepmath#33]
Hi, I am currently working on the RL training loop. Is it possible that anyone can share with me the basic idea of what does deepmath.deephol.deephol_loop.missing.runner do in the training loop? Also, is the RL an online training or offline training? @kbansal

**Comment by kbansal** [comment]
The "deepmath.deephol.deephol_loop.missing.runner" should be replaced by one of the apache beam runners. You can read the HOList paper here about the exact RL setup: https://arxiv.org/abs/1904.03241, or the recap with images in this paper: https://arxiv.org/pdf/1905.10501.pdf

Feel free to re-open if you have other questions.
